### PR TITLE
GET basic auth from stac-fastapi.core

### PR DESCRIPTION
**Pull request by jonhealy1**
**Related Issue(s):**

- #

**Description:**

**PR Checklist:**

- [x] Code is formatted and linted (run `pre-commit run --all-files`)
- [x] Tests pass (run `make test`)
- [x] Documentation has been updated to reflect changes, if applicable
- [x] Changes are added to the changelog

### CODE REVIEW

**Comment by pedro-cf** [comment]
Greetings @jonhealy1 I see you are still working so I'll wait a bit to add some suggestions :)

**Comment by jonhealy1** [comment]
Hi @pedro-cf :) Go ahead now.

**Comment by jonhealy1** [comment]
A couple of the changes that belong here in this pr I pushed directly to main by mistake

**Comment by pedro-cf** [comment]
> Hi @pedro-cf :) Go ahead now.

- Revert the github workflow changes so we only have 1 testing step. Remove the step "Run test suite against Mongo w/ Basic Auth"
- Bring the improved basic_auth tests from sfeos to here aswell as the conftest.py changes. These conftest.py changes bring improved fixtures that include the environment variables needed for the basic_tests and therefore not needing an extra step in the github workflow

**Comment by jonhealy1** [comment]
Sounds really good. Do you want to add the changes to this pr?

**Comment by pedro-cf** [comment]
> Sounds really good. Do you want to add the changes to this pr?

ok sure

**Review by pedro-cf — COMMENTED** [review]
All good.

**Comment by pedro-cf** [comment]
You can merge @jonhealy1 I believe.

**Comment by jonhealy1** [comment]
Nice work thank you!

**Pull request merged**
